services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: homelibrary
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
      - db_logs:/var/log/postgresql
    networks:
      - homelibrary-net

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/homelibrary
    ports:
      - '4000:4000'
    networks:
      - homelibrary-net
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  db_data:
  db_logs:

networks:
  homelibrary-net:
    driver: bridge
